<div class="Layer5" style="width: 1111.53px; height: 968.36px; position: relative">
  <div class="ZLoat3BlurTexture2dsampleTex" style="left: 387.47px; top: 171.55px; position: absolute; transform: rotate(-120deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Z loat3 blur = Texture2DSample(Tex,)</div>
  <div class="ZOrIntI0IRI" style="left: 377.43px; top: 177.84px; position: absolute; transform: rotate(-122deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Z or (int i = 0; i < r; i++)</div>
  <div class="ZInput" style="left: 367.61px; top: 184.47px; position: absolute; transform: rotate(-124deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Z  = input;</div>
  <div class="ZEturnOrangebrightIncolor" style="left: 358.03px; top: 191.44px; position: absolute; transform: rotate(-126deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Z eturn OrangeBright(InColor);</div>
  <div class="ZUstomexpression" style="left: 348.70px; top: 198.74px; position: absolute; transform: rotate(-128deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Z ustomExpression#()</div>
  <div class="Group" style="width: 127.90px; height: 139.60px; left: 228.42px; top: 66.77px; position: absolute">
    <div class="ZEturnFuncScenetextureParameters" style="left: 111.20px; top: 139.60px; position: absolute; transform: rotate(-130deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Z eturn func(SceneTexture,Parameters);;</div>
    <div style="left: 119.48px; top: 132.65px; position: absolute; transform: rotate(-130deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">}</div>
  </div>
  <div class="ZEngineDProgramFiles" style="left: 330.82px; top: 214.29px; position: absolute; transform: rotate(-132deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Z Engine -> D:/Program Files/</div>
  <div class="YEturnFOut" style="left: 306.16px; top: 239.87px; position: absolute; transform: rotate(-138deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Y eturn f.Out();</div>
  <div class="YProgramFiles" style="left: 298.54px; top: 248.96px; position: absolute; transform: rotate(-140deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Y :/Program Files/</div>
  <div class="YProjectWarpmodeBlackbeyond" style="left: 291.26px; top: 258.29px; position: absolute; transform: rotate(-142deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Y Project/WarpMode/BlackBeyond/</div>
  <div class="YIrtualVoidStartupmoduleOverride" style="left: 284.30px; top: 267.88px; position: absolute; transform: rotate(-144deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Y irtual void StartupModule() override;</div>
  <div class="YProjectDimensionpathtest" style="left: 277.68px; top: 277.71px; position: absolute; transform: rotate(-146deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Y Project/DimensionPathTest/</div>
  <div class="YEngineGeneratedMaterialUsh" style="left: 271.41px; top: 287.76px; position: absolute; transform: rotate(-148deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Y /Engine/Generated/Material.ush</div>
  <div class="YEngineDProgramFiles" style="left: 265.49px; top: 298.03px; position: absolute; transform: rotate(-150deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Y /Engine -> D:/Program Files/</div>
  <div class="YDProgramFiles" style="left: 259.93px; top: 308.50px; position: absolute; transform: rotate(-152deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Y D:/Program Files/</div>
  <div class="YSm51ErrorInPreprocessor" style="left: 254.74px; top: 319.15px; position: absolute; transform: rotate(-154deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Y [SM5] 1 error in preprocessor.</div>
  <div class="XProjectWarpmodeBlackbeyond" style="left: 249.94px; top: 329.97px; position: absolute; transform: rotate(-156deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">X /Project/WarpMode/BlackBeyond/</div>
  <div class="XVirtualVoidStartupmoduleOverride" style="left: 245.50px; top: 340.97px; position: absolute; transform: rotate(-158deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">X virtual void StartupModule() override;</div>
  <div class="XAfrovoidism" style="left: 241.46px; top: 352.10px; position: absolute; transform: rotate(-160deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">X Afrovoidism</div>
  <div class="XEngineDProgramFiles" style="left: 237.80px; top: 363.37px; position: absolute; transform: rotate(-162deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">X /Engine -> D:/Program Files/ </div>
  <div class="XFromEnginePrivateBasepassvertexcommonUsh15" style="left: 234.55px; top: 374.76px; position: absolute; transform: rotate(-164deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">X from /Engine/Private/BasePassVertexCommon.ush: 15:</div>
  <div class="XProgramFiles" style="left: 231.68px; top: 386.26px; position: absolute; transform: rotate(-166deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">X :/Program Files/</div>
  <div class="XUrmentalvariable" style="left: 229.23px; top: 397.85px; position: absolute; transform: rotate(-168deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">X urMentalVariable;</div>
  <div class="WDProgramFilesWarpMode" style="left: 227.18px; top: 409.52px; position: absolute; transform: rotate(-170deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">W D:/Program Files/Warp Mode</div>
  <div class="WPixelshaderUsf" style="left: 225.54px; top: 421.25px; position: absolute; transform: rotate(-172deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">W PixelShader.usf</div>
  <div class="WProjectDimensionpathtest" style="left: 224.31px; top: 433.04px; position: absolute; transform: rotate(-174deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">W /Project/DimensionPathTest/</div>
  <div class="WCustomexpression" style="left: 223.48px; top: 444.86px; position: absolute; transform: rotate(-176deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">W CustomExpression#()</div>
  <div class="WDProgramFiles" style="left: 223.07px; top: 456.71px; position: absolute; transform: rotate(-178deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">W D:/Program Files/</div>
  <div class="WReturnFOut" style="left: 223.09px; top: 468.55px; position: absolute; transform: rotate(-180deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">W return f.Out();</div>
  <div class="WEngineDProgramFiles" style="left: 223.50px; top: 480.40px; position: absolute; transform: rotate(178deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">W /Engine -> D:/Program Files/</div>
  <div class="VProgramFiles" style="left: 224.34px; top: 492.21px; position: absolute; transform: rotate(176deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">V /Program Files/</div>
  <div class="VProjectWarpmodeBlackbeyond" style="left: 225.59px; top: 504px; position: absolute; transform: rotate(174deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">V Project/WarpMode/BlackBeyond/</div>
  <div class="VProjectDimensionpathtest" style="left: 227.24px; top: 515.73px; position: absolute; transform: rotate(172deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">V Project/DimensionPathTest/</div>
  <div class="VIrtualVoidStartupmoduleOverride" style="left: 229.30px; top: 527.39px; position: absolute; transform: rotate(170deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">V irtual void StartupModule() override;</div>
  <div class="VEngineDProgramFiles" style="left: 231.78px; top: 538.98px; position: absolute; transform: rotate(168deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">V /Engine -> D:/Program Files/</div>
  <div class="VProgramFiles" style="left: 234.65px; top: 550.48px; position: absolute; transform: rotate(166deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">V :/Program Files/</div>
  <div class="VSm51ErrorInPreprocessor" style="left: 237.92px; top: 561.87px; position: absolute; transform: rotate(164deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">V SM5] 1 error in preprocessor.</div>
  <div class="VUrmentalvariable" style="left: 241.59px; top: 573.13px; position: absolute; transform: rotate(162deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">V urMentalVariable;</div>
  <div class="UScenetextureFloat3" style="left: 245.65px; top: 584.27px; position: absolute; transform: rotate(160deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">U (SceneTexture, float3)</div>
  <div class="UDProgramFilesWarpMode" style="left: 250.09px; top: 595.25px; position: absolute; transform: rotate(158deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">U D:/Program Files/Warp Mode</div>
  <div class="UIrtualVoidStartupmoduleOverride" style="left: 254.92px; top: 606.07px; position: absolute; transform: rotate(156deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">U irtual void StartupModule() override;</div>
  <div class="UUstomexpression" style="left: 260.12px; top: 616.72px; position: absolute; transform: rotate(154deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">U ustomExpression#()</div>
  <div class="USm51ErrorInPreprocessor" style="left: 265.69px; top: 627.18px; position: absolute; transform: rotate(152deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">U SM5] 1 error in preprocessor.</div>
  <div class="UProgramFiles" style="left: 271.62px; top: 637.44px; position: absolute; transform: rotate(150deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">U :/Program Files/</div>
  <div class="UInput" style="left: 277.91px; top: 647.48px; position: absolute; transform: rotate(148deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">U  = input; </div>
  <div class="TUrmentalvariable" style="left: 284.54px; top: 657.30px; position: absolute; transform: rotate(146deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">T urMentalVariable;</div>
  <div class="TRomEnginePrivateBasepassvertexcommonUsh15" style="left: 291.51px; top: 666.88px; position: absolute; transform: rotate(144deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">T rom /Engine/Private/BasePassVertexCommon.ush: 15:</div>
  <div class="TProgramFiles" style="left: 298.81px; top: 676.21px; position: absolute; transform: rotate(142deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">T :/Program Files/</div>
  <div class="TProgramFilesWarpMode" style="left: 306.43px; top: 685.29px; position: absolute; transform: rotate(140deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">T :/Program Files/Warp Mode</div>
  <div class="TEngineDProgramFiles" style="left: 314.37px; top: 694.09px; position: absolute; transform: rotate(138deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">T Engine -> D:/Program Files/</div>
  <div class="SProjectWarpmodeBlackbeyond" style="left: 322.60px; top: 702.60px; position: absolute; transform: rotate(136deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">S Project/WarpMode/BlackBeyond/</div>
  <div class="SProgramFiles" style="left: 331.13px; top: 710.83px; position: absolute; transform: rotate(134deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">S :/Program Files/</div>
  <div class="SFronowismDmg" style="left: 339.95px; top: 718.75px; position: absolute; transform: rotate(132deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">S fronowism.dmg</div>
  <div class="SAterialfloat3Customexpression0" style="left: 349.02px; top: 726.37px; position: absolute; transform: rotate(130deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">S aterialFloat3 CustomExpression0(</div>
  <div class="SUrmentalvariable" style="left: 358.36px; top: 733.65px; position: absolute; transform: rotate(128deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">S urMentalVariable;</div>
  <div class="RProjectWarpmodeBlackbeyond" style="left: 367.96px; top: 740.61px; position: absolute; transform: rotate(126deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">R Project/WarpMode/BlackBeyond/</div>
  <div class="RScenetextureFloat3" style="left: 377.78px; top: 747.23px; position: absolute; transform: rotate(124deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">R SceneTexture, float3)</div>
  <div class="RProjectDimensionpathtest" style="left: 387.83px; top: 753.50px; position: absolute; transform: rotate(122deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">R Project/DimensionPathTest/</div>
  <div class="REngineGeneratedMaterialUsh" style="left: 398.10px; top: 759.42px; position: absolute; transform: rotate(120deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">R Engine/Generated/Material.ush</div>
  <div class="RUstomexpression" style="left: 408.57px; top: 764.98px; position: absolute; transform: rotate(118deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">R ustomExpression#()</div>
  <div class="RUrmentalvariable" style="left: 419.22px; top: 770.17px; position: absolute; transform: rotate(116deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">R urMentalVariable;</div>
  <div class="QFrovoidismExe" style="left: 430.05px; top: 774.98px; position: absolute; transform: rotate(114deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Q frovoidism.exe</div>
  <div class="QEturnFOut" style="left: 441.03px; top: 779.41px; position: absolute; transform: rotate(112deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Q eturn f.Out();</div>
  <div class="QEturnFOut" style="left: 452.18px; top: 783.46px; position: absolute; transform: rotate(110deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Q eturn f.Out();</div>
  <div class="QProgramFiles" style="left: 463.45px; top: 787.11px; position: absolute; transform: rotate(108deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Q :/Program Files/</div>
  <div class="QFronowismExe" style="left: 474.84px; top: 790.37px; position: absolute; transform: rotate(106deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Q fronowism.exe</div>
  <div class="QUstomexpression" style="left: 486.33px; top: 793.23px; position: absolute; transform: rotate(104deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">Q ustomExpression#()</div>
  <div class="PEngineDProgramFiles" style="left: 497.92px; top: 795.68px; position: absolute; transform: rotate(102deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">P Engine -> D:/Program Files/</div>
  <div class="PEngineDProgramFiles" style="left: 509.59px; top: 797.73px; position: absolute; transform: rotate(100deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">P Engine -> D:/Program Files/</div>
  <div class="PProjectWarpmodeBlackbeyond" style="left: 521.33px; top: 799.37px; position: absolute; transform: rotate(98deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">P Project/WarpMode/BlackBeyond/</div>
  <div class="PEturnFOut" style="left: 533.12px; top: 800.60px; position: absolute; transform: rotate(96deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">P eturn f.Out();</div>
  <div class="PEturnFOut" style="left: 544.94px; top: 801.43px; position: absolute; transform: rotate(94deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">P eturn f.Out();</div>
  <div class="PProgramFilesWarpMode" style="left: 556.78px; top: 801.83px; position: absolute; transform: rotate(92deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">P :/Program Files/Warp Mode</div>
  <div class="OUrmentalvariable" style="left: 568.63px; top: 801.82px; position: absolute; transform: rotate(90deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">O urMentalVariable;</div>
  <div class="OEturnFOut" style="left: 580.47px; top: 801.41px; position: absolute; transform: rotate(88deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">O eturn f.Out()</div>
  <div class="OProjectDimensionpathtest" style="left: 592.29px; top: 800.57px; position: absolute; transform: rotate(86deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">O Project/DimensionPathTest/</div>
  <div class="OOrIntI0IRI" style="left: 604.07px; top: 799.32px; position: absolute; transform: rotate(84deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">O or (int i = 0; i < r; i++)</div>
  <div class="OSm51ErrorInPreprocessor" style="left: 615.80px; top: 797.67px; position: absolute; transform: rotate(82deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">O SM5] 1 error in preprocessor.</div>
  <div class="ONgineDProgramFiles" style="left: 627.47px; top: 795.60px; position: absolute; transform: rotate(80deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">O ngine -> D:/Program Files/</div>
  <div class="NScenetextureFloat3" style="left: 639.06px; top: 793.13px; position: absolute; transform: rotate(78deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">N SceneTexture, float3)</div>
  <div class="NOrIntI0IRI" style="left: 650.55px; top: 790.25px; position: absolute; transform: rotate(76deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">N or (int i = 0; i < r; i++)</div>
  <div class="NUrmentalvariable" style="left: 661.94px; top: 786.98px; position: absolute; transform: rotate(74deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">N urMentalVariable;</div>
  <div class="NProgramFilesWarpMode" style="left: 673.21px; top: 783.31px; position: absolute; transform: rotate(72deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">N :/Program Files/Warp Mode</div>
  <div class="NFrofuturismExe" style="left: 684.35px; top: 779.25px; position: absolute; transform: rotate(70deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">N frofuturism.exe</div>
  <div class="MUrmentalvariable" style="left: 695.32px; top: 774.81px; position: absolute; transform: rotate(68deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">M urMentalVariable;</div>
  <div class="MEngineGeneratedMaterialUsh" style="left: 706.15px; top: 769.98px; position: absolute; transform: rotate(66deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">M Engine/Generated/Material.ush</div>
  <div class="MAterialfloat3Customexpression0" style="left: 716.79px; top: 764.79px; position: absolute; transform: rotate(64deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">M aterialFloat3 CustomExpression0(</div>
  <div class="MProgramFilesWarpMode" style="left: 727.26px; top: 759.22px; position: absolute; transform: rotate(62deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">M :/Program Files/Warp Mode</div>
  <div class="MRomEnginePrivateBasepassvertexcommonUsh15" style="left: 737.51px; top: 753.28px; position: absolute; transform: rotate(60deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">M rom /Engine/Private/BasePassVertexCommon.ush: 15:</div>
  <div class="LProjectWarpmodeBlackbeyond" style="left: 747.55px; top: 747px; position: absolute; transform: rotate(58deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">L Project/WarpMode/BlackBeyond/</div>
  <div class="LEturnFOut" style="left: 757.37px; top: 740.37px; position: absolute; transform: rotate(56deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">L eturn f.Out();</div>
  <div class="LProjectDimensionpathtest" style="left: 766.95px; top: 733.39px; position: absolute; transform: rotate(54deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">L Project/DimensionPathTest/</div>
  <div class="LDProgramFiles" style="left: 776.28px; top: 726.09px; position: absolute; transform: rotate(52deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">L D:/Program Files/</div>
  <div class="LVirtualVoidStartupmoduleOverride" style="left: 785.35px; top: 718.48px; position: absolute; transform: rotate(50deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">L virtual void StartupModule() override;</div>
  <div class="LMaterialfloat3Customexpression0" style="left: 794.16px; top: 710.54px; position: absolute; transform: rotate(48deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">L MaterialFloat3 CustomExpression0(</div>
  <div class="LReturnFOut" style="left: 802.67px; top: 702.30px; position: absolute; transform: rotate(46deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">L return f.Out();</div>
  <div class="KEturnOrangebrightIncolor" style="left: 810.90px; top: 693.78px; position: absolute; transform: rotate(44deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">K eturn OrangeBright(InColor);</div>
  <div class="KOrIntI0IRI" style="left: 818.82px; top: 684.96px; position: absolute; transform: rotate(42deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">K or (int i = 0; i < r; i++)</div>
  <div class="KProgramFiles" style="left: 826.43px; top: 675.88px; position: absolute; transform: rotate(40deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">K :/Program Files/</div>
  <div class="KUstomexpression" style="left: 833.73px; top: 666.54px; position: absolute; transform: rotate(38deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">K ustomExpression#()</div>
  <div class="Group" style="width: 152.77px; height: 110.59px; left: 827.86px; top: 656.95px; position: absolute">
    <div class="KEturnFuncScenetextureParameters" style="left: 12.81px; top: 0px; position: absolute; transform: rotate(36deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">K eturn func(SceneTexture,Parameters);;</div>
    <div style="left: 6.47px; top: 8.74px; position: absolute; transform: rotate(36deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">}</div>
  </div>
  <div class="KIrtualVoidStartupmoduleOverride" style="left: 847.30px; top: 647.12px; position: absolute; transform: rotate(34deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">K irtual void StartupModule() override;</div>
  <div class="JUblicdependencymodulenamesAddrange" style="left: 853.58px; top: 637.07px; position: absolute; transform: rotate(32deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">J ublicDependencyModuleNames.AddRange</div>
  <div class="JEngineDProgramFiles" style="left: 859.49px; top: 626.81px; position: absolute; transform: rotate(30deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">J Engine -> D:/Program Files/</div>
  <div class="JInput" style="left: 865.05px; top: 616.33px; position: absolute; transform: rotate(28deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">J  = input;</div>
  <div class="Group" style="width: 164.15px; height: 85.29px; left: 860.68px; top: 605.68px; position: absolute">
    <div class="JEturnFuncScenetextureParameters" style="left: 9.56px; top: 0px; position: absolute; transform: rotate(26deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">J eturn func(SceneTexture,Parameters);;</div>
    <div style="left: 4.82px; top: 9.71px; position: absolute; transform: rotate(26deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">}</div>
  </div>
  <div class="JRomEnginePrivateBasepassvertexcommonUsh15" style="left: 875.05px; top: 594.86px; position: absolute; transform: rotate(24deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">J rom /Engine/Private/BasePassVertexCommon.ush: 15:</div>
  <div class="IInput" style="left: 879.48px; top: 583.87px; position: absolute; transform: rotate(22deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">I  = input;</div>
  <div class="IAterialfloat3Customexpression0" style="left: 883.53px; top: 572.73px; position: absolute; transform: rotate(20deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">I aterialFloat3 CustomExpression0(</div>
  <div class="IOrIntI0IRI" style="left: 887.18px; top: 561.46px; position: absolute; transform: rotate(18deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">I or (int i = 0; i < r; i++)</div>
  <div class="ILoat3BlurTexture2dsampleTexTexsamplerUv" style="left: 890.44px; top: 550.07px; position: absolute; transform: rotate(16deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">I loat3 blur = Texture2DSample(Tex, TexSampler, UV);</div>
  <div class="IL5ongsen8end09wFoGr09und" style="left: 893.30px; top: 538.57px; position: absolute; transform: rotate(14deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">I l5ongsen8end09w FO$GR09und**</div>
  <div class="ISm51ErrorInPreprocessor" style="left: 895.76px; top: 526.98px; position: absolute; transform: rotate(12deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">I SM5] 1 error in preprocessor.</div>
  <div class="HLocateAfroportals23" style="left: 897.80px; top: 515.31px; position: absolute; transform: rotate(10deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">H Locate:Afroportals.<23*></div>
  <div class="HEngineDProgramFiles" style="left: 899.45px; top: 503.58px; position: absolute; transform: rotate(8deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">H /Engine -> D:/Program Files/</div>
  <div class="HInput" style="left: 900.68px; top: 491.79px; position: absolute; transform: rotate(6deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">H  = input;</div>
  <div class="HEturnFOut" style="left: 901.50px; top: 479.97px; position: absolute; transform: rotate(4deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">H eturn f.Out();</div>
  <div class="HFronowismExe" style="left: 901.90px; top: 468.13px; position: absolute; transform: rotate(2deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">H fronowism.exe</div>
  <div class="HFwdTimeloopLoop" style="left: 901.90px; top: 456.28px; position: absolute; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">H >fwd>timeloop>[loop]</div>
  <div class="Group" style="width: 174.28px; height: 27.86px; left: 901.47px; top: 438.36px; position: absolute">
    <div class="GEturnFuncScenetextureParameters" style="left: 0px; top: 6.07px; position: absolute; transform: rotate(-2deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">G eturn func(SceneTexture,Parameters);;</div>
    <div style="left: 0.38px; top: 16.87px; position: absolute; transform: rotate(-2deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">}</div>
  </div>
  <div class="GUrmentalvariable" style="left: 900.64px; top: 432.62px; position: absolute; transform: rotate(-4deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">G urMentalVariable;</div>
  <div class="GEturnFOut" style="left: 899.40px; top: 420.84px; position: absolute; transform: rotate(-6deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">G eturn f.Out();</div>
  <div class="G1212FfffGFssghmXz" style="left: 897.74px; top: 409.10px; position: absolute; transform: rotate(-8deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">G 1212);ffff>G>>?FSSGHM XZ</div>
  <div class="GRoamingNewworldDmg" style="left: 895.68px; top: 397.44px; position: absolute; transform: rotate(-10deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">G Roaming_newworld.dmg</div>
  <div class="F12718237935djsk" style="left: 893.21px; top: 385.85px; position: absolute; transform: rotate(-12deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">F 12718237935djsk(*)</div>
  <div class="FNewexpressionVoidism" style="left: 890.33px; top: 374.35px; position: absolute; transform: rotate(-14deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">F NewExpression(voidism)</div>
  <div class="FMaterialfloat3Customexpression0" style="left: 887.06px; top: 362.96px; position: absolute; transform: rotate(-16deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">F MaterialFloat3 CustomExpression0(</div>
  <div class="FPoc" style="left: 883.39px; top: 351.70px; position: absolute; transform: rotate(-18deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">F POC_*(!!)</div>
  <div class="FANewload7Futurism" style="left: 879.33px; top: 340.56px; position: absolute; transform: rotate(-20deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">F a_newload7 FUTurism</div>
  <div class="ENowismAct0r1e" style="left: 874.88px; top: 329.59px; position: absolute; transform: rotate(-22deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">E nowism act0r1e</div>
  <div class="EVirtualVoidStartupmoduleOverride" style="left: 870.06px; top: 318.76px; position: absolute; transform: rotate(-24deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">E virtual void StartupModule() override;</div>
  <div class="EBlurTexture2dsampleTexTexsamplerUvFloat2" style="left: 864.85px; top: 308.11px; position: absolute; transform: rotate(-26deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">E blur += Texture2DSample(Tex, TexSampler, UV + float2)</div>
  <div class="EDProgramFilesWarpMode" style="left: 859.28px; top: 297.65px; position: absolute; transform: rotate(-28deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">E D:/Program Files/Warp Mode</div>
  <div class="DMaterialfloat3" style="left: 853.36px; top: 287.40px; position: absolute; transform: rotate(-30deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">D MaterialFloat3</div>
  <div class="DBeyondEnterLcc" style="left: 847.07px; top: 277.35px; position: absolute; transform: rotate(-32deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">D Beyond/enter.lcc</div>
  <div class="DBeyondBlack" style="left: 840.44px; top: 267.53px; position: absolute; transform: rotate(-34deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">D beyond_blACK</div>
  <div class="DBCirclesN" style="left: 833.47px; top: 257.95px; position: absolute; transform: rotate(-36deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">D B_circles.n</div>
  <div class="CEngineDProgramFiles" style="left: 826.17px; top: 248.62px; position: absolute; transform: rotate(-38deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">C Engine -> D:/Program Files/</div>
  <div class="CTiimeisNowww" style="left: 818.54px; top: 239.55px; position: absolute; transform: rotate(-40deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">C tiIMEis_noWWW</div>
  <div class="CTimewarp" style="left: 810.61px; top: 230.75px; position: absolute; transform: rotate(-42deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">C TIMEwarp</div>
  <div class="CProjectDimensionpathtest" style="left: 802.38px; top: 222.23px; position: absolute; transform: rotate(-44deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">C /Project/DimensionPathTest/</div>
  <div class="BAa" style="left: 793.84px; top: 214px; position: absolute; transform: rotate(-46deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">B AA</div>
  <div class="B1010px" style="left: 785.03px; top: 206.08px; position: absolute; transform: rotate(-48deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">B _1010px</div>
  <div class="BDirectPastFillFuture" style="left: 775.95px; top: 198.47px; position: absolute; transform: rotate(-50deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">B direct past (Fill_future)</div>
  <div class="BDEngineDProgramFiles" style="left: 766.61px; top: 191.18px; position: absolute; transform: rotate(-52deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">B d /Engine -> D:/Program Files/</div>
  <div class="ADirect10xAfrofuturusm" style="left: 757.02px; top: 184.22px; position: absolute; transform: rotate(-54deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">A direct 10x AFROFUTURUSM</div>
  <div class="AProjectWarpmodeBlackbeyond" style="left: 747.20px; top: 177.61px; position: absolute; transform: rotate(-56deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">A /Project/WarpMode/BlackBeyond/</div>
  <div class="AWarpmodeDmg" style="left: 737.15px; top: 171.33px; position: absolute; transform: rotate(-58deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">A (WarpMode.dmg)</div>
  <div class="APublicdependencymodulenamesAddrange" style="left: 726.87px; top: 165.41px; position: absolute; transform: rotate(-60deg); transform-origin: 0 0; color: white; font-size: 9px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">A PublicDependencyModuleNames.AddRange</div>
  <div class="Black" style="left: 529.86px; top: 438.32px; position: absolute; color: white; font-size: 20.94px; font-family: AUTHENTIC Sans; font-weight: 400; word-wrap: break-word">BlaCK</div>
  <div class="Beyond" style="left: 529.75px; top: 460.16px; position: absolute; color: white; font-size: 20.94px; font-family: AUTHENTIC Sans; font-weight: 600; word-wrap: break-word">bEyonD_</div>
</div>
